"""add commitment

Revision ID: 5dc633e5fe76
Revises: e7226a8c2497
Create Date: 2026-06-03 22:57:37.351032

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import finance_web_app.domain.money

revision: str = '5dc633e5fe76'
down_revision: str | None = 'e7226a8c2497'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', finance_web_app.domain.money.MoneyPence(), nullable=False),
    sa.Column('category', sa.Enum('OCCASIONAL', 'GROCERIES', 'CLOTHING', 'ENTERTAINMENT', 'PETROL', 'KIDS', 'CHRISTMAS', name='category'), nullable=False),
    sa.Column('recurrence', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', 'ONCE_ONLY', name='recurrence'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_stop', sa.Date(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('OCCASIONAL', 'GROCERIES', 'KIDS', 'ENTERTAINMENT', 'CLOTHING')", name='commitment_category_valid'),
    sa.CheckConstraint("recurrence IN ('DAILY', 'WEEKLY', 'MONTHLY', 'ANNUAL', 'ONCE_ONLY')", name='commitment_recurrence_valid'),
    sa.CheckConstraint('effective_stop >= effective_from', name='commitment_effective_range'),
    sa.CheckConstraint('length(name) > 0', name='commitment_name_nonempty'),
    sa.CheckConstraint('quantity >= 0', name='commitment_quantity_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commitment')
    # ### end Alembic commands ###
