"""add income and income_exception

Revision ID: 601a6302441d
Revises: 5dc633e5fe76
Create Date: 2026-06-03 23:05:36.392336

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import finance_web_app.domain.money



revision: str = '601a6302441d'
down_revision: str | None = '5dc633e5fe76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', finance_web_app.domain.money.MoneyPence(), nullable=False),
    sa.Column('recurrence', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', 'ONCE_ONLY', name='recurrence'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_stop', sa.Date(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.CheckConstraint("recurrence IN ('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', 'ONCE_ONLY')", name='income_recurrence_valid'),
    sa.CheckConstraint('effective_stop IS NULL OR effective_stop >= effective_from', name='income_effective_range'),
    sa.CheckConstraint('length(name) > 0', name='income_name_nonempty'),
    sa.CheckConstraint('quantity >= 0', name='income_quantity_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', finance_web_app.domain.money.MoneyPence(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='income_exception_quantity_nonneg'),
    sa.ForeignKeyConstraint(['income_id'], ['income.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('income_id', 'date', name='income_exception_unique_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_exception')
    op.drop_table('income')
    # ### end Alembic commands ###
