"""initial schema

Revision ID: 7e38f73399b5
Revises: 
Create Date: 2026-06-03 17:17:48.800713

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import finance_web_app.domain.money

revision: str = '7e38f73399b5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', finance_web_app.domain.money.MoneyPence(), nullable=False),
    sa.Column('category', sa.Enum('OCCASIONAL', 'GROCERIES', 'CLOTHING', 'ENTERTAINMENT', 'PETROL', 'KIDS', 'CHRISTMAS', name='category'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_stop', sa.Date(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('OCCASIONAL', 'GROCERIES', 'CLOTHING', 'ENTERTAINMENT', 'PETROL', 'KIDS', 'CHRISTMAS')", name='budget_category_valid'),
    sa.CheckConstraint('effective_stop IS NULL OR effective_stop >= effective_from', name='budget_effective_range'),
    sa.CheckConstraint('length(name) > 0', name='budget_name_nonempty'),
    sa.CheckConstraint('quantity >= 0', name='budget_quantity_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(password_hash) > 0', name='user_password_hash_nonempty'),
    sa.CheckConstraint('length(username) > 0', name='user_username_nonempty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('budget')
    # ### end Alembic commands ###
