"""add expense

Revision ID: e7226a8c2497
Revises: 7e38f73399b5
Create Date: 2026-06-03 22:46:09.881019

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import finance_web_app.domain.money

revision: str = 'e7226a8c2497'
down_revision: str | None = '7e38f73399b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', finance_web_app.domain.money.MoneyPence(), nullable=False),
    sa.Column('category', sa.Enum('OCCASIONAL', 'GROCERIES', 'CLOTHING', 'ENTERTAINMENT', 'PETROL', 'KIDS', 'CHRISTMAS', name='category'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('OCCASIONAL', 'GROCERIES', 'CLOTHING', 'ENTERTAINMENT', 'PETROL', 'KIDS', 'CHRISTMAS')", name='expense_category_valid'),
    sa.CheckConstraint('length(name) > 0', name='expense_name_nonempty'),
    sa.CheckConstraint('quantity >= 0', name='expense_quantity_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    # ### end Alembic commands ###
